// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TygaSoft.Repositories;

namespace TygaSoft.Api.Migrations
{
    [DbContext(typeof(SqliteContext))]
    partial class SqliteContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024");

            modelBuilder.Entity("TygaSoft.Model.DbTables.OrdersInfo", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("ApplicationId");

                    b.Property<DateTime>("CreatedDate");

                    b.Property<string>("Ip");

                    b.Property<string>("IpPlace");

                    b.Property<DateTime>("LastUpdatedDate");

                    b.Property<string>("Latlng");

                    b.Property<string>("LatlngPlace");

                    b.Property<string>("OrderCode");

                    b.Property<string>("OrderStatus");

                    b.Property<string>("ParentOrderCode");

                    b.Property<string>("Pictures");

                    b.Property<string>("Siblings");

                    b.Property<string>("UserId");

                    b.HasKey("Id")
                        .HasName("PrimaryKey_OrdersId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("TygaSoft.Model.DbTables.UsersInfo", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("ApplicationId");

                    b.Property<DateTime>("CreatedDate");

                    b.Property<string>("Email");

                    b.Property<DateTime>("LastUpdatedDate");

                    b.Property<string>("MobilePhone");

                    b.Property<string>("Name");

                    b.Property<string>("Password");

                    b.Property<int>("PasswordFormat");

                    b.Property<string>("PasswordSalt");

                    b.Property<string>("Roles");

                    b.Property<int>("_Id");

                    b.HasKey("Id")
                        .HasName("PrimaryKey_UsersId");

                    b.ToTable("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
